package io.code.sutra.activity.service;
import ch.qos.logback.core.net.server.Client;
import io.code.sutra.activity.repository.TaskRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import io.code.sutra.activity.entity.Task;
import io.code.sutra.activity.util.IdGenerator;

@Slf4j
@Service
@RequiredArgsConstructor
public class TaskService {

    private final TaskRepository taskRepository;
    private final NotificationService notificationService;

    public List<Task> getAllTasks() {
        return taskRepository.findAll();
    }

    public Optional<Task> getTaskById(Long id) {
        return taskRepository.findById(id);
    }
    public List<Task> getTaskByAssignee(String name) {
        return taskRepository.findByAssignee(name);
    }

    public List<Task> getTasksByStatus(String status) {
        return taskRepository.findByStatus(status);
    }

   public Task createTask(Task task) {
        // Log the incoming task details (input)
        if (task != null) {
            log.info("createTask called with input -> id: {}, title: {}, status: {}, assignee: {}, service: {}",
                    task.getId(), task.getTitle(), task.getStatus(), task.getAssignee(), task.getService());
        } else {
            log.info("createTask called with null task");
            throw new IllegalArgumentException("Task cannot be null");
        }

        // Validate required fields so JPA doesn't fail with a low-level exception
        List<String> missing = new ArrayList<>();
        if (task.getTitle() == null || task.getTitle().isBlank()) missing.add("title");
        if (task.getStatus() == null || task.getStatus().isBlank()) missing.add("status");
        if (task.getService() == null || task.getService().isBlank()) missing.add("service");
        if (!missing.isEmpty()) {
            String msg = "Missing required Task fields: " + String.join(",", missing);
            log.warn("createTask validation failed: {}", msg);
            throw new IllegalArgumentException(msg);
        }

        // Ensure an identifier is assigned before persisting (Task.id is not generated by JPA)
        if (task.getId() == null) {
            long generated = IdGenerator.getNextId();
            task.setId(generated);
            log.info("Assigned generated id {} to task before persist", generated);
        }

        Task savedTask = taskRepository.save(task);
        if (notificationService != null) {
            notificationService.notify("Task created successfully", "success");
        }
        log.info("Task persisted with id {}", savedTask.getId());
        return savedTask;
    }

    public Task updateTask(Long id, Task taskUpdates) {
        return taskRepository.findById(id)
            .map(existingTask -> {
                if (taskUpdates.getTitle() != null) {
                    existingTask.setTitle(taskUpdates.getTitle());
                }
                if (taskUpdates.getStatus() != null) {
                    existingTask.setStatus(taskUpdates.getStatus());
                }
                if (taskUpdates.getAssignee() != null) {
                    existingTask.setAssignee(taskUpdates.getAssignee());
                }
                Task updated = taskRepository.save(existingTask);
                if (notificationService != null) {
                    notificationService.notify("Task updated successfully", "success");
                }
                return updated;
            })
            .orElse(null);
    }

    public Task assignTask(Long id, String assignee) {
        return taskRepository.findById(id)
            .map(existingTask -> {
                existingTask.setAssignee(assignee);
                Task updated = taskRepository.save(existingTask);
                if (notificationService != null) {
                    notificationService.notify("Task assigned to " + assignee, "info");
                }
                return updated;
            })
            .orElse(null);
    }

    public boolean deleteTask(Long id) {
        if (taskRepository.existsById(id)) {
            taskRepository.deleteById(id);
            if (notificationService != null) {
                notificationService.notify("Task deleted successfully", "success");
            }
            return true;
        }
        return false;
    }
}